name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --deploy --dev

      - name: Set Environment Variables
        run: echo "DATABASE_URL=sqlite:///${{ github.workspace }}/db.sqlite3" >> $GITHUB_ENV

      - name: Debugging
        run: |
          echo "Checking Environment Variables"
          env | grep DATABASE_URL
          echo "Checking Python Version"
          python --version
          echo "Checking Pipenv Virtual Environment"
          pipenv --venv || echo "Pipenv environment not found"
  
      - name: Apply Migrations
        run: |
          pipenv shell --quiet
          pipenv run python manage.py migrate
  
      - name: Run Tests
        run: |
          pipenv shell --quiet
          pipenv run python manage.py test

